apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: privaterepo
  url: https://github.com/grant-cl/k8s-homelab.git
  password: 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
  username: grant-cl
